In [ ]:
# 0._ Añadimos la ruta de la raiz del proyecto para poder importar los modulos

In [8]:
import sys
import os

# Añadir la raíz del proyecto al path
ROOT = os.path.abspath("../../")
if ROOT not in sys.path:
    sys.path.append(ROOT)

print("Ruta añadida:", ROOT)

Ruta añadida: d:\WorkTable\Curso\GitHub_Pontia\ML Practica Only

In [ ]:
# 1._ Importar librerias y cargar dataset

In [9]:
import pandas as pd
from pathlib import Path

# Ruta al dataset original
DATA_PATH = Path("../../data/raw/dataset_practica_final.csv")

df = pd.read_csv(DATA_PATH)

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [ ]:
# 2._ Entrenamos los modelos

In [10]:
import importlib
import src.model_trainer
importlib.reload(src.model_trainer)

In [11]:
from src.model_trainer import train_models

results, best_model = train_models(df)

Entrenando modelo: Logistic Regression
Entrenando modelo: Decision Tree
Entrenando modelo: Random Forest
Entrenando modelo: Gradient Boosting
Entrenando modelo: Neural Network

d:\WorkTable\Curso\GitHub_Pontia\ML Practica Only\venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(

In [ ]:
# 3._ Mostramos los resultados de cada modelo
# en principio deberiamos de obtener una tabla con accuracy, precision, recall, f1-score y roc_auc

In [12]:
import pandas as pd

pd.DataFrame(results).T

                     accuracy  precision    recall        f1   roc_auc
Logistic Regression  0.818368   0.810982  0.664556  0.730504  0.896182
Decision Tree        0.858824   0.807390  0.812776  0.810074  0.851453
Random Forest        0.893961   0.892746  0.811193  0.850018  0.957787
Gradient Boosting    0.850909   0.850976  0.724364  0.782582  0.926849
Neural Network       0.868708   0.842080  0.794573  0.817637  0.941973

In [ ]:
# 4._ Guardar la info del mejor modelo

In [13]:
import os

os.listdir("../../models")

['best_model.pkl',
 'decision_tree.pkl',
 'gradient_boosting.pkl',
 'logistic_regression.pkl',
 'neural_network.pkl',
 'random_forest.pkl']

In [14]:
# nos debe de indicar que la info del mejor modelo se ha guardado en la carpeta models, con el nombre best_model.pkl

print("Entrenamiento completado. El mejor modelo ha sido guardado en /models/best_model.pkl")

Entrenamiento completado. El mejor modelo ha sido guardado en /models/best_model.pkl